name: Python Evn Utils

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: [fmt, lint, mypy]
    env:
      TOXENV: ${{ matrix.toxenv }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python (3.11)
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install and run tox
        run: |
          pip install tox
          tox

  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["38", "39", "310", "311", "312"]

    env:
      TOXENV: py${{ matrix.python }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install and run tox
        run: |
          pip install tox
          tox
